services:
  next_app:
    container_name: next_app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    # environment:
    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - express_server
    links:
      - express_server
    networks:
      - app-network

  express_server:
    container_name: express_server
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app-network

  loadbalancer:
    container_name: loadbalancer
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - express_server
      - next_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
