services:
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/app
    links:
      - redis
    ports:
      - "5000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      IO_TOKEN_SECRET: ${IO_TOKEN_SECRET}

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - server
