services:
  server-john:
    build:
      context: ./server
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - "81:5000"
    environment:
      - NAME=John
      - MONGODB_URI=${MONGODB_URI}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - IO_TOKEN_SECRET=${IO_TOKEN_SECRET}

  server-paul:
    build:
      context: ./server
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - "82:5000"
    environment:
      - NAME=Paul

  server-george:
    build:
      context: ./server
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - "83:5000"
    environment:
      - NAME=George

  server-ringo:
    build:
      context: ./server
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - "84:5000"
    environment:
      - NAME=Ringo

  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      WATCHPACK_POLLING: ${WATCHPACK_POLLING}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      NEXT_PUBLIC_API_ENDPOINT: ${NEXT_PUBLIC_API_ENDPOINT}

    # Set environment variables based on the .env file
    env_file:
      - .env
    restart: always
    ports:
      - 3000:3000

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - server-john
      - server-paul
      - server-george
      - server-ringo
