import { Inter } from "next/font/google";
import "./globals.css";
import ToastContainer from "@/components/atoms/Toast";
import Tooltip from "@/components/atoms/Tooltip";
import { apiOptions } from "@/lib/api";
import { cookies } from "next/headers";
import { AuthProvider } from "@/providers/auth/AuthProvider";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const loadUserFromSession = async () => {
  "use server";
  if (typeof window !== "undefined") {
    return;
  }

  const sessionCookie = cookies().get("dfr_hub_session");
  if (!sessionCookie) {
    return { user: null, sessionCookie };
  }

  try {
    const res = await axios.get("/api/auth/loaduserfromsession", {
      ...apiOptions,
      baseURL: process.env.NEXT_PUBLIC_LOAD_BALANCER,
      headers: {
        ...apiOptions.headers,
        Cookie: `${sessionCookie.name}=${sessionCookie.value};`,
      },
    });
    return { user: res.data, sessionCookie };
  } catch (e) {
    return { user: null, sessionCookie };
  }
};

export default async function RootLayout({ children }) {
  const session = await loadUserFromSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider session={session}>{children}</AuthProvider>
        <ToastContainer />
        <Tooltip id="tooltip" className="z-50" />
      </body>
    </html>
  );
}
